### ISSUE TITLE
crash conditions

### ISSUE THREAD

**Issue by sunderme** [astoeckel/texstudio_poppler_crash_bug#1]
The original code did not crash at all.
I have changed the page dpi to 20.0 and add a wait period after filling the queue.
That leads to 1 in 5 runs to crash (8 cores).

**Comment by astoeckel** [comment]
Thank you for testing!

So the issue must really depend on the number of available hardware threads, the code crashes quite reproducibly on my machine (with 16C/32T). It also tended to crash much more often with the non-stripped down version (i.e., commit a7e557a4634b9751da8265da5508f8660c0b81e4), suggesting some weird timing issue. But so is life with race conditions.

**Comment by sunderme** [comment]
I have reported the bug to poppler: https://gitlab.freedesktop.org/poppler/poppler/-/issues/1050.
Let's see what the feedback is.

**Comment by astoeckel** [comment]
Sounds good, thank you!
